[workspace]
members = [
    # Fpr web-backend
    "website/backend",
    # For rustyc
    "compilers/rustyc/frontend",
    "compilers/rustyc/backend",
    "compilers/rustyc/interpreter",
    "compilers/rustyc/optimizer",
    # For Calculator toy lang
    "compilers/calculator",
    # For rustypy
    # For jsbridge
    "others/js-bridge",
]
resolver = "2"
