[workspace]
members = [
    ## For Toy Lang
    "toy-lang/backend",
    "toy-lang/compiler",
    ## For script body
    "script-boy",
    ## For JSBridge
    "JSbridge",
    #### For JSBridge examples
    "JSbridge/examples/string_passing",
]
