[workspace]
members = [
    # For rustyc
    "compilers/rustyc/frontend",
    "compilers/rustyc/backend",
    "compilers/rustyc/interpreter",
    # For jsbridge
    "others/js-bridge",
    "others/js-bridge/examples/string-passing",
    # For souring rs

]
