[workspace]
members = [
    # Fpr web-backend
    "website/backend",
    # For rustyc
    "compilers/rustyc/frontend",
    "compilers/rustyc/backend",
    "compilers/rustyc/interpreter",
    "compilers/rustyc/optimizer",
    # For Calculator toy lang
    "compilers/calculator",
    # For jsbridge
    "others/js-bridge",
    # For souring rs

    # For all labs
    ## for lab of compiler
    "labs/compiler/value-numbering",
    "labs/compiler/shared-data-structure"
    ## for js-brige label

]
resolver = "2"
