[package]
name = "rustyc-shared"
description = "contain Token, AST and IR for rustyc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
