name: "Basic Test For Web-Infras Packages"
on: ["pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Install Deps
        uses: "./.github/install-node-dep"
      - name: Run Linter on Common Package
        run: yarn lint
        working-directory: "web-infras/common"
      - name: Run Linter on Parser Package
        run: yarn lint
        working-directory: "web-infras/parser"
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Install Deps
        uses: "./.github/install-node-dep"
      - name: Run Linter on Common Package
        run: yarn format
        working-directory: "web-infras/common"
      - name: Run Linter on Parser Package
        run: yarn format
        working-directory: "web-infras/parser"
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Install Deps
        uses: "./.github/install-node-dep"
      - name: Run Test on Parser Package
        run: yarn test:ci
        working-directory: "web-infras/parser"